require('dotenv').config();
const express = require('express');
const cors = require('cors');

const authRoutes = require('./src/routes/auth');
const adminRoutes = require('./src/routes/admin');
const meRoutes = require('./src/routes/me');
const scheduleRoutes = require('./src/routes/schedule');
const createRoutes = require('./src/routes/create');
const tipsFactsRoutes = require('./src/routes/tipsFacts');
const cardsRoutes = require('./src/routes/cards');
const testFetchRoutes = require('./src/routes/testFetch');
const testPipelineRoutes = require('./src/routes/testPipeline');
const testPhase3Routes = require('./src/routes/testPhase3');
const pipelineGenerateNowRoutes = require('./src/routes/pipelineGenerateNow');
const { startScheduler } = require('./src/services/cronScheduler');

const app = express();

app.use(cors({ origin: process.env.FRONTEND_ORIGIN || 'http://localhost:3000' }));
app.use(express.json());

// Serves the fallback card images generated by services/imageHandler.js
// (backend/public/generated/*.png) at http://localhost:4000/generated/...
// — this was missing entirely, which meant every fallback-generated image
// URL 404'd and silently fell back to the placeholder icon in the UI.
app.use('/generated', express.static(require('path').join(__dirname, 'public', 'generated')));

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', service: 'scoopr-backend' });
});

app.use('/api/auth', authRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/me', meRoutes);
app.use('/api/schedule', scheduleRoutes);
app.use('/api/create', createRoutes);
app.use('/api/tips-facts', tipsFactsRoutes);

// Phase 4, Prompt 2: read-only, paginated card listing for the Feed tab.
// (See routes/cards.js — this was genuinely missing before this prompt;
// everything else so far only ever wrote to `cards`, never read it back.)
app.use('/api/cards', cardsRoutes);

// Phase 3, Cron Engine: manual "Generate Now" — runs the pipeline
// immediately for the logged-in user using their saved schedule_settings.
app.use('/api/pipeline', pipelineGenerateNowRoutes);

// TEMPORARY (Phase 2, prompt 1): manual test endpoint for the Reddit/RSS
// fetchers. No auth — remove or protect once real aggregation exists.
app.use('/api/test', testFetchRoutes);
app.use('/api/test', testPipelineRoutes);

// Phase 3, Prompt 6 (Final Consolidation + Robustness): one consolidated,
// authenticated status-check across everything Prompts 1-5 built —
// GET /api/test/phase3-status. Mounted after the scheduler-independent
// test routes above but this one is auth-required (see testPhase3.js),
// unlike testFetch/testPipeline.
app.use('/api/test', testPhase3Routes);

app.use((req, res) => {
  res.status(404).json({ error: 'Route not found.' });
});

const PORT = process.env.PORT || 4000;
app.listen(PORT, () => {
  console.log(`Scoopr backend running on http://localhost:${PORT}`);

  // Phase 3, Cron Engine: start polling schedule_settings for due users.
  // Started here (after the server is actually listening) rather than
  // above app.listen so a scheduler startup issue never prevents the API
  // itself from coming up — see PHASE3_CRON_ENGINE_README.md.
  startScheduler();
});
