import React from 'react';
import { Card } from '../ui';

/**
 * Shown when History has zero cards. R5 only ever had one case here
 * ("No history yet" — a brand-new account with nothing in the `cards`
 * table). Redesign Phase, Prompt 6 brings back the second case its
 * header comment always said would return alongside search/filters: a
 * `filtered` prop, true when the archive genuinely has cards but the
 * current search text and/or topic/source-type pills matched none of
 * them, so the person sees "no results" rather than the same "you've
 * never generated anything" copy.
 */
export default function HistoryEmptyState({ filtered = false }) {
  return (
    <Card style={{ textAlign: 'center', padding: 'var(--space-6) var(--space-5)' }}>
      <p style={{ fontSize: 16, fontWeight: 600, marginBottom: 'var(--space-2)' }}>
        {filtered ? 'No matching history' : 'No history yet'}
      </p>
      <p style={{ color: 'var(--color-text-muted)', fontSize: 14, lineHeight: 1.6 }}>
        {filtered
          ? 'Try a different search term or clear the filters above.'
          : 'Cards generated by the pipeline, or ones you create yourself, will show up here.'}
      </p>
    </Card>
  );
}
